### ISSUE TITLE
No complete view of balances

### ISSUE THREAD

**Issue by sixtysix76** [beanieboi/moneymoney-bitfinex#4]
Moneymoney only shows 2 currencies from Bitfinex. Even with new API, new purchased currencies aren’t shown.

**Comment by beanieboi** [comment]
hey,

could you please provide some logs from MoneyMoneyApp? I use it with 6 currencies without a problem.

thanks
ben

**Comment by ussjonas** [comment]
HI, i have a similar error, out of 4 tokens, 1 is not shown. 
Can you help?

**Comment by beanieboi** [comment]
can you tell me the tokens that are missing. i will try to troubleshoot the problem.

**Comment by ussjonas** [comment]
the token is named FUN, FunFair
Thank you

**Comment by beanieboi** [comment]
sorry for the super late response. I updated the supported tokens. you should have a complete list now
