### ISSUE TITLE
Does not work after update

### ISSUE THREAD

**Issue by sixtysix76** [beanieboi/moneymoney-bitfinex#6]
Hi Benjamin,

had the same issue, that many tokens were not shown (NEO, IOTA, Golem...).
Now i copied the update into my library and it does not work. MoneyMoney does not show the plugin in Extensions

**Comment by beanieboi** [comment]
can you look into the MoneyMoney Log (Window->Log) and see if there are some errors (red lines)
I'm using the latest version with 7 tokens and it works on my computer.

**Comment by sixtysix76** [comment]
Ignoring 'bitfinex.lua' because signature verification failed.

**Comment by beanieboi** [comment]
I will try to contact the MoneyMoney team and will ask them to sign the new version

**Comment by beanieboi** [comment]
I got a signature from the MoneyMoney Team, can you please try downloading the latest copy from master

**Comment by sixtysix76** [comment]
Works perfect, thx!!

**Comment by schmeusel** [comment]
Using the latest copy from master, it says in the log that the signature verification is failing. Could you request a new signature?
